### ISSUE TITLE
iscu files don't show document icons

### ISSUE THREAD

**Issue by castdrian** [castdrian/ishare#11]
document icons and text are configured and should show up, but iscu files still just render as blank docs

**Comment by iGerman00** [comment]
It's caching. No modifications to the build were made, system icon cache cleared and the result is:
<img width="687" alt="image" src="https://github.com/castdrian/ishare/assets/36676880/9af58816-9066-44d9-bf60-35bc16c01ed8">

Commands used to force an icon cache clear:
```bash
sudo rm -rfv /Library/Caches/com.apple.iconservices.store
sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3;sudo touch /Applications/* ; killall Dock; killall Finder
```
