### ISSUE TITLE
plugin ecosystem

### ISSUE THREAD

**Issue by castdrian** [castdrian/ishare#17]
allow scripted plugins for users to further process media

**Comment by zisra** [comment]
Is this related to #18?

**Comment by castdrian** [comment]
no

**Comment by castdrian** [comment]
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingCode/Concepts/AboutLoadableBundles.html#//apple_ref/doc/uid/20001268-BCIDBAEJ
