### ISSUE TITLE
proper toast notifications

### ISSUE THREAD

**Issue by castdrian** [castdrian/ishare#20]
needs to wait for https://github.com/BlueHuskyStudios/BHBezelNotification/issues/6 and https://github.com/BlueHuskyStudios/BHBezelNotification/issues/5

**Comment by KyLeggiero** [comment]
https://github.com/BlueHuskyStudios/BHBezelNotification/issues/5 is about to be resolved by https://github.com/BlueHuskyStudios/BHBezelNotification/issues/7!! 🥳 

Regarding https://github.com/BlueHuskyStudios/BHBezelNotification/issues/6, you can use a workaround like this until official support is added:

```swift
import SwiftUI
import BezelNotification



struct SomeView: View {
    @State
    private var showBezel: Bool

    var body: some View {
        Button("Start") {
            showBezel = true
        }
        .onChange(showBezel) { shouldShow in
            guard shouldShow else { return }

            BezelNotification.show(messageText: "Starting...", icon: .myStartingIcon) {
                showBezel = false
            }
        }
    }
}
```
