### ISSUE TITLE
Change default opening directory when exporting settngs

### ISSUE THREAD

**Issue by favna** [castdrian/ishare#23]
The default directory that finder opens when exporting settings is the same as the screen captures capture path. This is often either `~/Pictures` or a subfolder of it and is likely also not the directory you would want to export a plist file to.

All that said, I would recommend changing the default directory that Finder opens to `~/Documents` or `~/Desktop` (I think the former is an iCloud Drive thing so it might not always be available, not entirely sure)

**Comment by castdrian** [comment]
settngs kek
