### ISSUE TITLE
uploader UI is broken

### ISSUE THREAD

**Issue by Oneloutre** [castdrian/ishare#44]
**Describe the bug**
When I try to add a value to "header" it simply crashes

**To Reproduce**
1. Go to "settings"
2. Click on "add an uploader"
3. add a value to header

**Expected behavior**
I'd like to append my api key for my server X)

**Screenshots**

https://github.com/castdrian/ishare/assets/54822802/dd836cc3-edf0-4bc7-9207-3143a2237c7e

**Desktop (please complete the following information):**
 - OS: MacOs Ventura 13.4.1
 - Browser (don't use but Arc)
 - Version : last == 1.4.6
 

**Additional context**

**Comment by Oneloutre** [comment]
Actually I'm even trying to set it up to get it working with an ASS server, directly editing the iscu file but... I can't, I don't know why. Maybe I'm missing something, I don't really know what is feasible compared to shareX....

**Comment by nackerr** [comment]
It works fine when doing it from the file directly. Here's how I do mine:


{
    "name": "Ryan.bet",
    "requestUrl": "https:\/\/myexampleurl.com\/myfile.php",
    "headers": { "Authorization": "Bearer my token" },
    "id": "blah blah",
    "responseProp": "url"
}

**Comment by Oneloutre** [comment]
HMMMM
I'm gonna try again, thanks. what is "id" for, please ?

**Comment by nackerr** [comment]
It looks like it's the item ID. My suggestion would be to create a new one, export the file, and make your edits, then upload the file.

**Comment by Oneloutre** [comment]
Yep It's what I'm trying to do 👍 I'll let you know if I manage to do it

**Comment by Oneloutre** [comment]
Okay, now it is loaded by the app but I get an error while testing the uploader. Do you use ASS server you too ? (https://github.com/tycrek/ass)

**Comment by Oneloutre** [comment]
update : cloudflare seems to be annoying (I ran a test with postman but it's really weird, curl works fine)

**Comment by castdrian** [comment]
the ui is fucked, do not use it, my apologies I'm a terrible UI designer so just write json until someone decides to fix it

**Comment by Oneloutre** [comment]
yeah okay lmao

**Comment by Oneloutre** [comment]
(I just wrote on the discord it's more convenient I think)

**Comment by AakifNadeem** [comment]
@castdrian  @Oneloutre I have created a new working UI. Please let me know if you like some changes.

https://github.com/castdrian/ishare/assets/58801997/46d7677e-834d-4280-abb9-dcebe63b3a27
