### ISSUE TITLE
History UI bugged (not showing picture, just a warning)

### ISSUE THREAD

**Issue by Oneloutre** [castdrian/ishare#47]
**Describe the bug**
History UI is bugged when a screenshot or capture is taken with custom uploader (not tried with local store) it's not showing picture, just a warning. (see the screen below)

**To Reproduce**
1. Click the Ishare icon
2. Click on history

**Expected behavior**
I guess we should see something else ? like an icon with the capture or a link if it's custom uploader

**Screenshots**
<img width="1440" alt="Capture d’écran 2023-10-04 à 18 48 42" src="https://github.com/castdrian/ishare/assets/54822802/d3183be6-6d69-4ee2-b6e2-89b3fc605850">

**Desktop (please complete the following information):**
 - OS: MacOs Sonoma but it was not working with MacOs 13 neither since I did the update tomorrow
 - Browser: Arc

**Comment by castdrian** [comment]
nor bugged, your urls just don't return images

**Comment by Oneloutre** [comment]
<img" alt="Capture d’écran" src=" https://cdn.onelots.fr/u/2023-10-05_09:46:45.png">

actually, they are 🤔
