### ISSUE TITLE
Nothing happens when opening the app

### ISSUE THREAD

**Issue by JakubKoralewski** [castdrian/ishare#55]
**Describe the bug**
Nothing happens when opening the app. I can see some process in resource monitor, I can kill it and it is properly killed. It once asked me whether I want updates to be installed automatically I checked yes and continued, but that's it.

**To Reproduce**
1. Download 3.0.0
2. Hold control and open the app.

**Expected behavior**
Welcome screen? Some guide?

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1
 - Browser downloaded with Safari
 - Version 3.0.0

**Comment by JakubKoralewski** [comment]
Hm I just had too many apps opened in whatever the top right icon corner is called in MacOS and ishare was cut off. I closed a couple of things and it showed up :) Still would a welcome screen would be nice.

**Comment by castdrian** [comment]
Well it is designed as menu bar app so like that's where it presents itself, currently there are no plans to have a window pop out on first launch but I won't deny a PR if you wish to open one
