### ISSUE TITLE
Allow switching to window capture mode when in region capture

### ISSUE THREAD

**Issue by floogulinc** [castdrian/ishare#56]
**Is your feature request related to a problem? Please describe.**
In the default screenshot utility on macOS when you're selecting a region you can press space to switch to selecting a window. In iShare right now the region capture mode is locked to only region capture and the window capture mode is only window capture.

**Describe the solution you'd like**
I would like option to have the ability to switch between region and window capture with space in iShare. I think using `screencapture -i` rather than `screencapture -s` would be sufficient. 

**Describe alternatives you've considered**
I could use the built in screenshot functionality in macOS but it doesn't have the ability to both save to a file and copy to clipboard at the same time.

**Comment by castdrian** [comment]
Will have a look at that

**Comment by castdrian** [comment]
turns out it does indeed work properly now

**Comment by floogulinc** [comment]
Thanks!

**Comment by floogulinc** [comment]
Thanks!
