### ISSUE TITLE
feat: application logs

### ISSUE THREAD

**Issue by DevQuandt** [castdrian/ishare#57]
**Is your feature request related to a problem? Please describe.**
My Problem is when I try to create a new json for my uploader it seems to be no longer working. I migrated the json like mentioned in the Readme.MD.
I can try a sample upload but the error does not help with trouble shooting "An error occurred during the upload process."

**Describe the solution you'd like**
Have application logs to see what request the application does and what response it receives.

**Comment by castdrian** [comment]
You should be able to see logs via Console but I do agree a log file in the application directory is a good idea
