### ISSUE TITLE
Provide a simple example for a self-made uploader

### ISSUE THREAD

**Issue by Jay2k1** [castdrian/ishare#65]
I found ishare when I looked for a tool that lets me 
- capture a window, region or screen
- upload this screenshot to my webserver (preferably via FTP/SFTP)
- copy the URL to the image to my clipboard

On Windows, I use ShareX for that. On the mac, I had written an AppleScript that uses the built-in CLI screenshot command `screencapture -i`, `scp` to upload and `pbcopy` to copy the file name into the clipboard. Due to the increasing permissions needed to capture a screenshot, this stopped working properly (macOS requested permissions to screenshot for the app I tried to screenshot instead of my script), so I googled for a tool again and found ishare.

My issue was that I couldn't find instructions on what I would need to set up on the server side of things, so I tested a bit and came up with this simple PHP:
```php
<?php
// uploader.php
$uploaddir = 'uploads/';
$fileFormName = 'file'; // default: 'file' if not set in ishare uploader config
// ------------------------------------------------------------
// handle file deletion
if (isset($_GET['delete'])) {
    $file = $uploaddir . $_GET['delete'];
    if (file_exists($file) && is_writable($file)) {
        unlink($file);
    }
    die();
}

// handle file uploading
if (move_uploaded_file($_FILES[$fileFormName]['tmp_name'], $uploaddir . $_FILES[$fileFormName]['name'])) {
    echo '{"fileId":"' . $_FILES[$fileFormName]['name'] . '"}';
} else {
    echo '{"fileId":"an error occured on the server"}';
}
```
This works with an uploader config like this:
```json
{
        "name": "custom PHP file uploader",
        "responseURL": "https://my-uploader.tld/uploads/{{fileId}}",
        "deletionURL": "https://my-uploader.tld/uploader.php?delete={{fileId}}",
        "requestURL": "https://my-uploader.tld/uploader.php"
}
```

Maybe an example like this could be added to the readme for people like me that would like to self-host their screenshots. Or maybe a project wiki would be a better place, so people could add working example configs for other upload services :)

**Comment by castdrian** [comment]
confirmed to be compatible services are already listed
