### ISSUE TITLE
resizing a window during screen recording stops the recording and the video is not working.

### ISSUE THREAD

**Issue by ldenoue** [castdrian/ishare#69]
**Describe the bug**
Resizing a recorded window makes the app produce invalid MP4 and stops the recording immediately.

**To Reproduce**
1. Pick a window to record
2. Start the recording
3. Resize the window during the recording
4. See error: the app stops recording and the mp4 is invalid

**Expected behavior**
The app should not crash and keep recording the resized window.

**Screenshots**
None.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by castdrian** [comment]
CNR
