### ISSUE TITLE
iSharexZipline

### ISSUE THREAD

**Issue by BraidenCodez15** [castdrian/ishare#83]
when using my zipline server to upload the screenshots I get this error on my clipboard

**_failed%20to%20extract%20json%20value%20for%20files%5B0%5D_**

The config that I am using to use zipline is down below
https://github.com/castdrian/ishare/issues/62

after editing it here is my copy (token nulled out)
https://cdn.eastcoastbraiden.me/u/UmM88i.png

**Comment by BraidenCodez15** [comment]
found out i did not edit the full domain

**Comment by sahara101** [comment]
What did you configure for the clipboard? I cannot get it to work. Thanks!
