### ISSUE TITLE
Issues with zipline

### ISSUE THREAD

**Issue by sahara101** [castdrian/ishare#88]
**Describe the bug**
Hello,

zipline clipboard does not paste the image URL

**To Reproduce**
Create a zipline connection using below settings:
```
{
  "requesturl": "https://zipline.mydomain.org/api/upload",
  "id": "some-string",
  "name": "Zipline",
  "headers": {
    "Authorization": "TOKEN",
    "Original-Name": "true",
    "Format": "random",
    "Embed": "true"
  },
  "fileformname": "file",
  "responseurl": "{{files[0]}}"
}
```

**Expected behavior**

When pasting the clipboard to have the correct zipline screenshot URL. I am suing V4. 

**Screenshots**
This is what it pastes now:

![](https://zipline.rlvd.duckdns.org/u/GpjvOr.png)

**Desktop (please complete the following information):**
 MacOS 15 beta
Version 4.0.1 (55)

Thanks!

**Comment by sahara101** [comment]
Still having the issue :(

**Comment by castdrian** [comment]
incomprehensible English and undetailed issue template, furthermore unstable OS version

**Comment by sahara101** [comment]
Ok thank you for the update and the lack of support interest. Answering after 1 week with this response is laughable. Time to search another application.
