### ISSUE TITLE
feat: keybinds for "Capture and Upload"

### ISSUE THREAD

**Issue by lenisko** [castdrian/ishare#91]
Extend allowed keybinds with "Capture and upload" by adding "Upload modifier key" as explained in https://github.com/castdrian/ishare/issues/91#issuecomment-2506844470

This way we can have ShareX like double layer to auto upload only desired captures after they are taken.

**Comment by castdrian** [comment]
don't particularly like this idea, adding a shortcut to toggle the uploading task is probably a better solution

**Comment by lenisko** [comment]
- **Pros:** easier, faster, you don't have to remember value of toggle from previous interaction
- **Cons:** doubles the hotkeys forms for anything related to Capture/Record

Something between... maybe modifier key? Which would trigger upload when it's down during execution of normal shortkey.

So only one new shortkey would be added `Upload key modifier` - when pressed down during execution of other shortkey it would upload a result to host. Going by example assigns in first post, having it set to `SHIFT` image would be uploaded on `shift+cmd+1`

**Comment by castdrian** [comment]
I like that idea a lot better, also quite aligned with the actual purpose of modifiers

**Comment by lenisko** [comment]
Agree, would be much cleaner with current design.

I took the initial idea from my hotkeys list of ShareX - it allows creating a customized hotkey to almost every action, so it makes sense to use it like that.

**Comment by Car-Role** [comment]
Is this feature live? I haven't been able to find it
